// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq10FlmVbqBEFwWm8b99awCBLrjohrCEg',
    appId: '1:423107627908:web:d3de84449fa62a2871abd1',
    messagingSenderId: '423107627908',
    projectId: 'elnada-253e2',
    authDomain: 'elnada-253e2.firebaseapp.com',
    storageBucket: 'elnada-253e2.firebasestorage.app',
    measurementId: 'G-Y0VDK78064',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOJPvU1pl4Vh4FfqRr7MKa2Mehq5WvBhU',
    appId: '1:423107627908:android:ee38c73571c9711871abd1',
    messagingSenderId: '423107627908',
    projectId: 'elnada-253e2',
    storageBucket: 'elnada-253e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH28azp9ekqKEa2FMAXFwKL2z6-xK83wM',
    appId: '1:423107627908:ios:25cffcf48d851d1f71abd1',
    messagingSenderId: '423107627908',
    projectId: 'elnada-253e2',
    storageBucket: 'elnada-253e2.firebasestorage.app',
    iosBundleId: 'com.example.elNada',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH28azp9ekqKEa2FMAXFwKL2z6-xK83wM',
    appId: '1:423107627908:ios:25cffcf48d851d1f71abd1',
    messagingSenderId: '423107627908',
    projectId: 'elnada-253e2',
    storageBucket: 'elnada-253e2.firebasestorage.app',
    iosBundleId: 'com.example.elNada',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq10FlmVbqBEFwWm8b99awCBLrjohrCEg',
    appId: '1:423107627908:web:24d7fa1289dc2d8b71abd1',
    messagingSenderId: '423107627908',
    projectId: 'elnada-253e2',
    authDomain: 'elnada-253e2.firebaseapp.com',
    storageBucket: 'elnada-253e2.firebasestorage.app',
    measurementId: 'G-GHD72NJXCD',
  );
}
